### ISSUE TITLE
Build error on arm with -Wcast-align

### ISSUE THREAD

**Issue by mtasaka** [gcmd/gnome-commander#21]
On arm 32 bit,  I still see build error with regard to -Werror=cast-align:
https://mtasaka.fedorapeople.org/Bugfix/gcmd/gcmd-build-arm.log.txt

For example,
```
/builddir/build/BUILD/gnome-commander-d9aa9269ec521b420ed1de0663cc45b80a17e6be/_builddir/../libgcmd/libgcmd-widget-factory.cc: In function 'GtkWidget* create_spin(GtkWidget*, const gchar*, gint, gint, gint)':
/usr/include/glib-2.0/gobject/gtype.h:2212:63: error: cast from 'GTypeInstance* {aka _GTypeInstance*}' to 'GtkAdjustment* {aka _GtkAdjustment*}' increases required alignment of target type [-Werror=cast-align]
     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
                                                               ^
/usr/include/glib-2.0/gobject/gtype.h:482:66: note: in expansion of macro '_G_TYPE_CIC'
 #define G_TYPE_CHECK_INSTANCE_CAST(instance, g_type, c_type)    (_G_TYPE_CIC ((instance), (g_type), c_type))
                                                                  ^~~~~~~~~~~
/usr/include/gtk-2.0/gtk/gtkadjustment.h:41:47: note: in expansion of macro 'G_TYPE_CHECK_INSTANCE_CAST'
 #define GTK_ADJUSTMENT(obj)                  (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_ADJUSTMENT, GtkAdjustment))
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/gnome-commander-d9aa9269ec521b420ed1de0663cc45b80a17e6be/_builddir/../libgcmd/libgcmd-widget-factory.cc:303:44: note: in expansion of macro 'GTK_ADJUSTMENT'
     GtkWidget *spin = gtk_spin_button_new (GTK_ADJUSTMENT (adj), 1, 0);
```

Here beginning with https://github.com/gcmd/gnome-commander/blob/master/libgcmd/libgcmd-widget-factory.cc#L300 , ``adj`` is created with ```gtk_adjustment_new ``` which probably has effectively type of ```GtkAdjustment*``` but actually the return type is ``GtkObject*``, which has smaller alignment of `` GtkAdjustment*``.  

How should we fix these errors (on arm 32bit)? 
*  Just ignore these when ``__arm__`` is defined?
*  Or, cast twice (like https://bugs.webkit.org/show_bug.cgi?id=43963 )?

**Comment by mtasaka** [comment]
Looks like we have to ignore these warnings with pragma: it seems that we cannot handle GLib internals.  And (while I don't have such machine) it seems these warnings that these warnings arises also on MIPS and so on.

So it seems that it is better that we ignore warnings from -Wcast-align on all architectures. Thoughts?

**Comment by mtasaka** [comment]
> -Wcast-align on all architectures

for the places we see warnings currently (only)

**Comment by turboscholz** [comment]
Hey,

thank you for digging into this! I had to read about this type of warning first, as I did not come in touch with it up to now. Now that I understand the problem, I would also suggest that we ignore these warnings with a pragma as we can not change something on the glib internals. I would say this is save. 

Thank you very much again!

**Comment by turboscholz** [comment]
Fixed already.
