### ISSUE TITLE
Isn't work when install from Ubuntu Software

### ISSUE THREAD

**Issue by sflash-biz** [gcmd/gnome-commander#36]
Hello.
Ubuntu 18.04, GNOME 3.28.2
After install from Ubuntu Software, nothing happened when I try launch Gnome Commander from it. + No program in search.

**Comment by turboscholz** [comment]
What is the output when you try to start it from within the gnome terminal?

**Comment by sflash-biz** [comment]
Hello.
Sorry looks like it not install it at all from ubuntu store. After `gnome-commander` ubuntu suggest install it again in terminal with apt!
Then when i run it:

> $ gnome-commander
> Gtk-Message: 01:28:52.344: Failed to load module "canberra-gtk-module"
> 
> (gnome-commander:5858): libgnomevfs-WARNING **: 01:28:52.377: Failed to activate daemon: The name org.gnome.GnomeVFS.Daemon was not provided by any .service files
> 
> ** (gnome-commander:5858): WARNING **: 01:28:52.377: Failed to open file “/home/user/.gnome-commander/gnome-commander.xml”: No such file or directory
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.378: GnomeCmdConRemote* gnome_cmd_con_remote_new(const gchar*, const string&, GnomeCmdCon::Authentication): assertion 'uri != NULL' failed
> 
> (gnome-commander:5858): GLib-GObject-WARNING **: 01:28:52.378: invalid (NULL) pointer instance
> 
> (gnome-commander:5858): GLib-GObject-CRITICAL **: 01:28:52.378: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.378: GnomeCmdConRemote* gnome_cmd_con_remote_new(const gchar*, const string&, GnomeCmdCon::Authentication): assertion 'uri != NULL' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.383: GnomeCmdBookmarkGroup* gnome_cmd_con_get_bookmarks(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.383: GnomeCmdPixmap* gnome_cmd_con_get_go_pixmap(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.383: const gchar* gnome_cmd_con_get_go_text(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.383: gboolean gnome_cmd_con_is_closeable(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.384: gboolean gnome_cmd_con_is_open(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.396: gboolean gnome_cmd_con_is_open(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.396: gboolean gnome_cmd_con_is_open(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.397: gboolean gnome_cmd_con_is_open(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.427: gboolean gnome_cmd_con_is_open(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.428: gboolean gnome_cmd_con_is_open(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.428: gboolean gnome_cmd_con_is_open(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.431: gboolean gnome_cmd_con_is_open(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.431: gboolean gnome_cmd_con_is_open(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
> ** (gnome-commander:5858): CRITICAL **: 01:28:52.432: gboolean gnome_cmd_con_is_open(GnomeCmdCon*): assertion 'GNOME_CMD_IS_CON (con)' failed
> 
>

**Comment by turboscholz** [comment]
So is it running now? If not it might be that gnome-vfs ist missing, but this is normal as this library is quite old. But from the above it looks as if it does not crash.

**Comment by turboscholz** [comment]
I'm closing this bug issue now. If the problem still persists, please open a bug report at Ubuntu. But as far as I know, the package is officially not supported in Ubuntu anymore. They only ship an [old version](https://packages.ubuntu.com/cosmic/gnome-commander) of Gnome Commander which is not supported by me anymore.
