### ISSUE TITLE
GNOME Commander & Ubuntu 21.04

### ISSUE THREAD

**Issue by daniilpetrov** [gcmd/gnome-commander#39]
When will you get rid of the obsolete libgnomevfs2-dev and finally be able to try GNOME Commander?
"Installing on Ubuntu 20.04" does not work - swears on the PGP-key...

**Comment by turboscholz** [comment]
Hi. Getting rid of Gnome-VFS is on the finish line. As you can see there are a lot of commits going in to this repository. But as Gnome Commander is heavily coupled to this old library, it is a huge amount of work to migrate to the successor library. I am working more than a year on this now.
