### ISSUE TITLE
POT file missing

### ISSUE THREAD

**Issue by zygimantus** [gcmd/gnome-commander#4]
There is no .pot file in po/ directory. How does one add a new language file then?

**Comment by turboscholz** [comment]
Thank you for your question. The direct link to the .pot file is [this](https://l10n.gnome.org/POT/gnome-commander.master/gnome-commander.master.pot) one. It is provided by the Gnomes [damned lies](https://l10n.gnome.org/module/gnome-commander/). Hope that helps. :)

**Comment by zygimantus** [comment]
Thank you very much @turboscholz!
