### ISSUE TITLE
Movement keybindings

### ISSUE THREAD

**Issue by antoine-gallix** [gcmd/gnome-commander#8]
A lot of action can be set to keybindings, but the most common one, "Move Up" and "Move Down" in the file list doesn't seem to be rebindable. It doesn't seems to be a big feature to add but it would be a big step forward for the user's choice in keyboard ergonomy.

**Comment by turboscholz** [comment]
Nice idea, shouldn't be that hard to implement. I'll keep you informed when the feature is ready :)

**Comment by antoine-gallix** [comment]
Nice! What a fast reaction!

**Comment by turboscholz** [comment]
Implemented in commit b6954ed. Thanks for the idea! :+1:

**Comment by antoine-gallix** [comment]
Wow, that was fast! Thank you.
